"""
API contract models for Aurelius Agent Backend.

This module defines Pydantic models for request/response validation
between the Godot client and Python backend.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Dict, List, Optional
from enum import Enum


class OriginType(str, Enum):
    """NPC origin types."""
    MIGRANT = "migrant"
    NATIVE = "native"
    REFUGEE = "refugee"


class EconomicFocus(str, Enum):
    """Economic behavior patterns."""
    HOARDING = "hoarding"
    INVESTING = "investing"
    SHARING = "sharing"
    SPENDING = "spending"


class TownContext(BaseModel):
    """Current town state metrics."""
    economic_index: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Economic health indicator (0-100)"
    )
    social_cohesion: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Social stability metric (0-100)"
    )
    karma_polarity: float = Field(
        ...,
        ge=-100.0,
        le=100.0,
        description="Moral alignment (-100 ruthless to +100 benevolent)"
    )
    dominant_theme: str = Field(
        ...,
        description="Town's current thematic state (e.g., 'industrial_ruin', 'pastoral_haven')"
    )


class OriginData(BaseModel):
    """NPC background origin information."""
    origin_type: OriginType = Field(
        ...,
        description="How the NPC came to be in this town"
    )
    parent_occupations: List[str] = Field(
        default_factory=list,
        description="Occupations of NPC's parents"
    )
    birth_location: str = Field(
        ...,
        description="Where the NPC was born"
    )


class SpawnAgentRequest(BaseModel):
    """Request to spawn a new NPC agent."""
    town_metrics: TownContext = Field(
        ...,
        description="Current state of the town"
    )
    origin_data: OriginData = Field(
        ...,
        description="NPC's background information"
    )


class PersonalityProfile(BaseModel):
    """NPC personality trait weights."""
    risk_aversion: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="How cautious the NPC is (0.0 = reckless, 1.0 = extremely cautious)"
    )
    cynicism: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Level of distrust in others (0.0 = trusting, 1.0 = deeply cynical)"
    )
    empathy: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Concern for others' wellbeing (0.0 = selfish, 1.0 = highly empathetic)"
    )
    ambition: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Drive to succeed (0.0 = content, 1.0 = highly ambitious)"
    )
    economic_focus: EconomicFocus = Field(
        ...,
        description="Primary economic behavior pattern"
    )

    @field_validator('risk_aversion', 'cynicism', 'empathy', 'ambition')
    @classmethod
    def validate_trait_range(cls, v: float) -> float:
        """Ensure trait values are within valid range."""
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"Trait value must be between 0.0 and 1.0, got {v}")
        return v


class AgentSpawnResponse(BaseModel):
    """Response containing newly spawned NPC data."""
    npc_id: str = Field(
        ...,
        description="Unique identifier for the NPC"
    )
    backstory_summary: str = Field(
        ...,
        min_length=50,
        description="3-paragraph backstory generated by Genesis workflow"
    )
    personality_weights: PersonalityProfile = Field(
        ...,
        description="Extracted personality traits"
    )
    initial_occupation: str = Field(
        ...,
        description="Starting job/role in the town"
    )
    starting_relationships: Dict[str, float] = Field(
        default_factory=dict,
        description="Initial relationships with other NPCs (npc_id -> affinity)"
    )


class InteractionContext(BaseModel):
    """Context for player-NPC interaction."""
    player_karma: float = Field(
        ...,
        ge=-100.0,
        le=100.0,
        description="Player's current karma value"
    )
    location: str = Field(
        ...,
        description="Where the interaction is taking place"
    )
    recent_player_actions: List[str] = Field(
        default_factory=list,
        max_length=5,
        description="Recent actions the player has taken"
    )


class DialogueRequest(BaseModel):
    """Request to generate dialogue options for an NPC."""
    npc_id: str = Field(
        ...,
        description="ID of the NPC being interacted with"
    )
    player_message: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="What the player said or did"
    )
    interaction_context: InteractionContext = Field(
        ...,
        description="Current interaction context"
    )


class DialogueOption(BaseModel):
    """A single dialogue response option."""
    response_type: str = Field(
        ...,
        description="Type of response (Empathetic, Pragmatic, Cynical, Antagonistic)"
    )
    text: str = Field(
        ...,
        min_length=10,
        max_length=300,
        description="The actual dialogue text"
    )
    karma_impact: float = Field(
        default=0.0,
        ge=-10.0,
        le=10.0,
        description="How this choice affects player karma"
    )


class DialogueResponse(BaseModel):
    """Response containing dialogue options."""
    npc_id: str = Field(
        ...,
        description="ID of the responding NPC"
    )
    options: List[DialogueOption] = Field(
        ...,
        min_length=4,
        max_length=4,
        description="Exactly 4 dialogue options"
    )
    emotional_state: Dict[str, float] = Field(
        default_factory=dict,
        description="NPC's current emotional state (joy, anger, fear, etc.)"
    )

    @field_validator('options')
    @classmethod
    def validate_option_count(cls, v: List[DialogueOption]) -> List[DialogueOption]:
        """Ensure exactly 4 dialogue options are provided."""
        if len(v) != 4:
            raise ValueError(f"Must provide exactly 4 dialogue options, got {len(v)}")
        return v


class AgentStateUpdate(BaseModel):
    """Request to update an agent's state."""
    npc_id: str = Field(
        ...,
        description="ID of the NPC to update"
    )
    world_context: Optional[TownContext] = Field(
        None,
        description="Updated world state"
    )
    trigger_reflection: bool = Field(
        default=False,
        description="Whether to trigger the reflection node"
    )


class AgentStateResponse(BaseModel):
    """Response containing updated agent state."""
    npc_id: str = Field(
        ...,
        description="ID of the NPC"
    )
    emotional_state: Dict[str, float] = Field(
        ...,
        description="Updated emotional state"
    )
    current_goal: str = Field(
        ...,
        description="NPC's current primary goal"
    )
    current_story_arc: int = Field(
        ...,
        ge=1,
        le=3,
        description="Current narrative act (1, 2, or 3)"
    )
